DEBUG                     = True 
SECRET_KEY                ="5L9g2Yrlaoc3X4z3N2WBtcDMul1453PW"
DATABASE                  ="wingo"
VERSION                   ="0.3"
VERSION_NAME              ="Pytheas"
RADIUS           		  =  {"small":50, "medium":500, "large":5000}
MAX_NOTE_LENGTH           = 255
NOTE_PER_PAGE             = 20
UPLOAD_FOLDER             = "uploads/"
UPLOAD_ALLOWED_EXTENSIONS = set(["png","jpg","jpeg","gif"])
